# Site settings
[params]
  # enter the path or leave empty string to disable -> ""
  # Example: "/images/logo.png"
  logo = ""

  # Enter number of posts to display per page.
  # Should be an unsigned integer.
  paginate = 10

  # Format of the date to display in the post list.
  # Please DO NOT change the numbers in the date format.
  # It must be 02 for day, Jan or 01 for month, 2006 for year
  # Examples 02 Jan 2006, 01/02/2006, 02-01-2006
  date_format = "2006-01-02"

  # A description of the site.
  description = ""
    
  twitterHandle = "@matusstafura"

[params.social]
    
  enabled = true
  twitter = true
  facebook = true

# Third party services
[params.verification]
  google = ""
  bing = ""

[params.plugins]
  # TAG MANAGER Google Tag Manager
  # Enter the full ID (like "GTM-XXXXXX")
  # or leave empty string to disable -> ""
  tagmanager = ""
