# Site settings
[params]
  # Enter number of posts to display per page.
  # Should be an unsigned integer.
  paginate = 10

  # A description of the site.
  description = "A personal blog."

# Third party services
[params.verification]
  google = ""
  bing = "XXX"

[params.plugins]
  # TAG MANAGER Google Tag Manager
  # Enter the full ID (like "GTM-XXXXXX")
  # or leave empty string to disable -> ""
  tagmanager = ""
