baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Jane's Blog"
theme = 'berg'
themesDir = '../..'

[params]
  logo = '/images/logo.svg'
  description = 'A simple, clean, and responsive Hugo theme.'
  date_format = 'January 2, 2006'
  breadcrumbs = false

[params.posts]
  showProfile = true

[params.author]
  name = "Jane Doe"
  bio = "Jane Doe is a creative and innovative author-blogger who specializes in design and programming. With a background in graphic design and computer science, Jane has a unique perspective on the intersection of these two fields."
  avatar = "/images/avatar.png"
  twitterHandle = "@janedoe"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.footer]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 1
