baseURL = 'example.org'
languageCode = 'en-us'
title = "Berg Docs"
theme = 'berg'
themesDir = '../..'

[params]
  logo = '/images/logo.svg'
  favicon = '/images/logo.svg'
  description = 'A documentation for a simple, clean, and responsive Hugo theme.'
  date_format = 'January 2, 2006'
  breadcrumbs = false
  custom_js = ['js/_custom.js']
  custom_css = ['css/_custom.css']
  showDarkModeToggle = true

[markup]
  [markup.highlight]
    style = 'github-dark'

[params.posts]
  showProfile = false

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Docs"
  url = "/docs/"
  weight = 2
[[menu.main]]
  name = "Demo"
  url = "https://berg.stafura.dev/"
  weight = 4

[[menu.footer]]
  name = "Privacy Policy"
  url = "/privacy-policy/"
  weight = 1
