baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Hugo Theme - Berg'
theme = 'berg'
themesDir = '../..'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
  [[menu.footer]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 1
  [[menu.footer]]
    name = "Cookie Policy"
    url = "/cookie-policy/"
    weight = 2
